reddit:
  baseUrl: https://old.reddit.com
  subreddit: worldnews
  postFilter:
    postLimit: 100
    minUpvotes: 500
    maxDownvotes: 500
    minUpvoteRatio: 0.70
    maxTimeHours: 4
lemmy:
  baseUrl: https://lemmy.world
  communityName: botlt_test@kbin.social